# Generated by Django 4.0 on 2022-02-18 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_product_category_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productQuantity', models.IntegerField(max_length=100)),
                ('ordered_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('customerName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.customer')),
                ('productName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='websites.product')),
            ],
        ),
    ]
