# Generated by Django 4.0 on 2022-02-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='Description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='productQuantity',
            field=models.IntegerField(),
        ),
    ]
