# Generated by Django 4.0 on 2022-02-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0007_alter_order_customername_alter_order_productname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentWay',
            field=models.CharField(choices=[('None', 'None'), ('Cash', 'Cash'), ('MobileBanking', 'MobileBanking'), ('Banking', 'Banking')], default='None', max_length=100),
        ),
    ]
