# Generated by Django 4.0 on 2022-02-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0008_alter_payment_paymentway'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered'), ('Completed', 'Completed'), ('Declined', 'Declined')], default='Pending', max_length=100),
        ),
    ]
